# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0003_auto_20180517_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='content',
            field=models.CharField(max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='username',
            field=models.CharField(max_length=32, null=None),
        ),
    ]
